package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 09:45:34
 * @Table batch_version
 */
public class BatchVersion {
    /**
     * id
     *
     * @mbg.generated 2019-04-02 09:45:34
     */
    private Integer id;

    /**
     * 任务名称: task_name
     *
     * @mbg.generated 2019-04-02 09:45:34
     */
    private String taskName;

    /**
     * 本版号: version
     *
     * @mbg.generated 2019-04-02 09:45:34
     */
    private Integer version;

    /**
     * create_time
     *
     * @mbg.generated 2019-04-02 09:45:34
     */
    private Date createTime;

    /**
     * update_time
     *
     * @mbg.generated 2019-04-02 09:45:34
     */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}