package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 14:13:02
 * @Table car
 */
public class Car {
    /**
     * 主键id: id
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Long id;

    /**
     * 车牌号: car_brand
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private String carBrand;

    /**
     * 服务id: so_id
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Integer soId;

    /**
     * 部门id: dept_id
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Integer deptId;

    /**
     * 部门名称: dept_name
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private String deptName;

    /**
     * 运输类型 1:冷鲜 2:百货 3:冷冻 4:冷库 5:蔬果 6:加班车辆 7:杭州-冷冻、冷藏 8:杭州-蔬果/百货: car_type
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Integer carType;

    /**
     * 创建时间: create_time
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Date createTime;

    /**
     * 更新时间: update_time
     *
     * @mbg.generated 2019-04-02 14:13:02
     */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCarBrand() {
        return carBrand;
    }

    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand;
    }

    public Integer getSoId() {
        return soId;
    }

    public void setSoId(Integer soId) {
        this.soId = soId;
    }

    public Integer getDeptId() {
        return deptId;
    }

    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public Integer getCarType() {
        return carType;
    }

    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}