package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 16:35:56
 * @Table car_avg_temperature
*/
public class CarAvgTemperature {
    /**
     * 主键id: id
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Long id;

    /**
     * 车牌号: car_brand
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private String carBrand;

    /**
     * 服务id: so_id
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Integer soId;

    /**
     * 运输类型 1:冷鲜 2:百货 3:冷冻 4:冷库 5:蔬果 6:加班车辆 7:杭州-冷冻、冷藏 8:杭州-蔬果/百货: car_type
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Integer carType;

    /**
     * 平均温度: mean_temperature
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Integer meanTemperature;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Date updateTime;

    /**
     * 未达标次数: below_standard_number
     * 
     * @mbg.generated 2019-04-03 16:35:56
      */
    private Integer belowStandardNumber;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCarBrand() {
        return carBrand;
    }

    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand;
    }

    public Integer getSoId() {
        return soId;
    }

    public void setSoId(Integer soId) {
        this.soId = soId;
    }

    public Integer getCarType() {
        return carType;
    }

    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    public Integer getMeanTemperature() {
        return meanTemperature;
    }

    public void setMeanTemperature(Integer meanTemperature) {
        this.meanTemperature = meanTemperature;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getBelowStandardNumber() {
        return belowStandardNumber;
    }

    public void setBelowStandardNumber(Integer belowStandardNumber) {
        this.belowStandardNumber = belowStandardNumber;
    }
}