package com.ddmc.kanban.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-04 10:52:01
 * @Table car_history_data
*/
public class CarHistoryData {
    /**
     * 主键id: id
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Long id;

    /**
     * 车牌号: car_brand
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private String carBrand;

    /**
     * 服务id: so_id
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Integer soId;

    /**
     * 运输类型 1:冷鲜 2:百货 3:冷冻 4:冷库 5:蔬果 6:加班车辆 7:杭州-冷冻、冷藏 8:杭州-蔬果/百货: car_type
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Integer carType;

    /**
     * 温度: temperature
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private BigDecimal temperature;

    /**
     * gps记录时间,运输车辆当前时间: gpstime
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Date gpstime;

    /**
     * 车辆所在的前置仓: station
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private String station;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-04 10:52:01
      */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCarBrand() {
        return carBrand;
    }

    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand;
    }

    public Integer getSoId() {
        return soId;
    }

    public void setSoId(Integer soId) {
        this.soId = soId;
    }

    public Integer getCarType() {
        return carType;
    }

    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    public BigDecimal getTemperature() {
        return temperature;
    }

    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    public Date getGpstime() {
        return gpstime;
    }

    public void setGpstime(Date gpstime) {
        this.gpstime = gpstime;
    }

    public String getStation() {
        return station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}