package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-03-29 15:06:07
 * @Table general_package
 */
public class GeneralPackage {
    /**
     * pack_id
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Integer packId;

    /**
     * store_id
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Integer storeId;

    /**
     * pack_title
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private String packTitle;

    /**
     * 更新人: update_user
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private String updateUser;

    /**
     * create_time
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Date createTime;

    /**
     * delivery_time
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Date deliveryTime;

    /**
     * update_time
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Date updateTime;

    /**
     * 状态, 0:待处理,1:已完成: status
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Integer status;

    /**
     * 类型: type
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Integer type;

    /**
     * 批次: batch_id
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private String batchId;

    /**
     * is_material
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private Integer isMaterial;

    /**
     * 商品json字符串,[{material_list:[{product_id,product_name,unit_name,is_batch,batch_list:[{batch_id,amount,whole_loss,corner_waste,vendor_id,vendor_name}],amount}],product_list:[{product_id,product_name,unit_name,is_batch,amount}]
     * }]: products
     *
     * @mbg.generated 2019-03-29 15:06:07
     */
    private String products;

    public Integer getPackId() {
        return packId;
    }

    public void setPackId(Integer packId) {
        this.packId = packId;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public String getPackTitle() {
        return packTitle;
    }

    public void setPackTitle(String packTitle) {
        this.packTitle = packTitle;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getBatchId() {
        return batchId;
    }

    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    public Integer getIsMaterial() {
        return isMaterial;
    }

    public void setIsMaterial(Integer isMaterial) {
        this.isMaterial = isMaterial;
    }

    public String getProducts() {
        return products;
    }

    public void setProducts(String products) {
        this.products = products;
    }
}