package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-04 13:32:58
 * @Table pest_inspection_mouse
*/
public class PestInspectionMouse {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private Integer id;

    /**
     * 鼠虫害周检查主表ID: inspection_id
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private Integer inspectionId;

    /**
     * 粘鼠板名称: name
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private String name;

    /**
     * 1、正常 2、捕获 0、无效: status
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private Integer status;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-04 13:32:58
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInspectionId() {
        return inspectionId;
    }

    public void setInspectionId(Integer inspectionId) {
        this.inspectionId = inspectionId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}