package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 19:33:35
 * @Table pest_inspection_mouse
*/
public class PestInspectionMouse {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private Integer id;

    /**
     * 鼠虫害周检查主表ID: pest_inspection_id
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private Integer pestInspectionId;

    /**
     * 粘鼠板名称: board_name
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private String boardName;

    /**
     * 1、正常 2、捕获 0、无效: status
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private Boolean status;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-02 19:33:35
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPestInspectionId() {
        return pestInspectionId;
    }

    public void setPestInspectionId(Integer pestInspectionId) {
        this.pestInspectionId = pestInspectionId;
    }

    public String getBoardName() {
        return boardName;
    }

    public void setBoardName(String boardName) {
        this.boardName = boardName;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}