package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 19:33:35
 * @Table pest_inspection
 */
public class PestInspection {
    /**
     * 自增长主键: id
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Integer id;

    /**
     * 前置门店ID: store_id
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Integer storeId;

    /**
     * 周起始日期: start_date
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Date startDate;

    /**
     * 周截止日期: end_date
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Date endDate;

    /**
     * 蚊虫情况：1 有，0 无: mosquito
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Boolean mosquito;

    /**
     * 处理措施: treatment
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private String treatment;

    /**
     * 操作人: operator
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private String operator;

    /**
     * 创建时间: create_time
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Date createTime;

    /**
     * 更新时间: update_time
     *
     * @mbg.generated 2019-04-02 19:33:35
     */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Boolean getMosquito() {
        return mosquito;
    }

    public void setMosquito(Boolean mosquito) {
        this.mosquito = mosquito;
    }

    public String getTreatment() {
        return treatment;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}