package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-12 16:49:58
 * @Table product_monitor_pid_temp
*/
public class ProductMonitorPidTemp {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-12 16:49:58
      */
    private Integer id;

    /**
     * 商品ID: product_id
     * 
     * @mbg.generated 2019-04-12 16:49:58
      */
    private Integer productId;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-12 16:49:58
      */
    private Date createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}