package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-18 09:33:27
 * @Table product_batch
*/
public class ProductBatch {
    /**
     * id
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Integer id;

    /**
     * 商品ID: product_id
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Integer productId;

    /**
     * 条码: product_code
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private String productCode;

    /**
     * batch_id
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private String batchId;

    /**
     * 保质期: quality_period
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Integer qualityPeriod;

    /**
     * 可售期: sale_period
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Integer salePeriod;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-18 09:33:27
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getBatchId() {
        return batchId;
    }

    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    public Integer getQualityPeriod() {
        return qualityPeriod;
    }

    public void setQualityPeriod(Integer qualityPeriod) {
        this.qualityPeriod = qualityPeriod;
    }

    public Integer getSalePeriod() {
        return salePeriod;
    }

    public void setSalePeriod(Integer salePeriod) {
        this.salePeriod = salePeriod;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}