package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 14:17:38
 * @Table refrigeration_house
*/
public class RefrigerationHouse {
    /**
     * id
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private Integer id;

    /**
     * 外部冷库（门店）ID: out_house_id
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private String outHouseId;

    /**
     * 外部冷库（门店）名称: out_house_name
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private String outHouseName;

    /**
     * 服务站: station_id
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private String stationId;

    /**
     * 1、生效；2、失效: status
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private Boolean status;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-02 14:17:38
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutHouseId() {
        return outHouseId;
    }

    public void setOutHouseId(String outHouseId) {
        this.outHouseId = outHouseId;
    }

    public String getOutHouseName() {
        return outHouseName;
    }

    public void setOutHouseName(String outHouseName) {
        this.outHouseName = outHouseName;
    }

    public String getStationId() {
        return stationId;
    }

    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}