package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 10:15:16
 * @Table refrigeration_house_gate
*/
public class RefrigerationHouseGate {
    /**
     * id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer id;

    /**
     * 座头鲸网关ID: out_gate_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String outGateId;

    /**
     * 网关名称: out_gate_name
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String outGateName;

    /**
     * 服务站: station_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String stationId;

    /**
     * 1、生效；2、失效: status
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Boolean status;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutGateId() {
        return outGateId;
    }

    public void setOutGateId(String outGateId) {
        this.outGateId = outGateId;
    }

    public String getOutGateName() {
        return outGateName;
    }

    public void setOutGateName(String outGateName) {
        this.outGateName = outGateName;
    }

    public String getStationId() {
        return stationId;
    }

    public void setStationId(String stationId) {
        this.stationId = stationId;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}