package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 10:15:16
 * @Table refri_house_summary_log
*/
public class RefriHouseSummaryLog {
    /**
     * id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer id;

    /**
     * 座头鲸网关ID: out_gate_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String outGateId;

    /**
     * 终端ID: terminal_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String terminalId;

    /**
     * 异常开始时间: yyyyMMddHHmmss: except_start_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Long exceptStartTime;

    /**
     * 本次计算最新采集时间：yyyyMMddHHmmss: current_collect_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Long currentCollectTime;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutGateId() {
        return outGateId;
    }

    public void setOutGateId(String outGateId) {
        this.outGateId = outGateId;
    }

    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public Long getExceptStartTime() {
        return exceptStartTime;
    }

    public void setExceptStartTime(Long exceptStartTime) {
        this.exceptStartTime = exceptStartTime;
    }

    public Long getCurrentCollectTime() {
        return currentCollectTime;
    }

    public void setCurrentCollectTime(Long currentCollectTime) {
        this.currentCollectTime = currentCollectTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}