package com.ddmc.kanban.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 10:15:16
 * @Table refri_house_dev_monitor
*/
public class RefriHouseDevMonitor {
    /**
     * id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer id;

    /**
     * 座头鲸网关ID: out_gate_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String outGateId;

    /**
     * 终端ID: terminal_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String terminalId;

    /**
     * 温度采集时间yyyyMMddHHmmss: collect_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Long collectTime;

    /**
     * 温度: temperature
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private BigDecimal temperature;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutGateId() {
        return outGateId;
    }

    public void setOutGateId(String outGateId) {
        this.outGateId = outGateId;
    }

    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public Long getCollectTime() {
        return collectTime;
    }

    public void setCollectTime(Long collectTime) {
        this.collectTime = collectTime;
    }

    public BigDecimal getTemperature() {
        return temperature;
    }

    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}