package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-02 14:17:38
 * @Table refri_house_except
 */
public class RefriHouseExcept {
    /**
     * id
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private Integer id;

    /**
     * 外部冷库（门店）ID: out_house_id
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private String outHouseId;

    /**
     * 终端ID: terminal_id
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private String terminalId;

    /**
     * 异常开始时间yyyyMMddHHmmss: start_time
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private Long startTime;

    /**
     * 异常结束时间yyyyMMddHHmmss: end_time
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private Long endTime;

    /**
     * 创建时间: create_time
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private Date createTime;

    /**
     * update_time
     *
     * @mbg.generated 2019-04-02 14:17:38
     */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutHouseId() {
        return outHouseId;
    }

    public void setOutHouseId(String outHouseId) {
        this.outHouseId = outHouseId;
    }

    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}