package com.ddmc.kanban.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 10:15:16
 * @Table refri_house_avg_temp
*/
public class RefriHouseAvgTemp {
    /**
     * id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer id;

    /**
     * 座头鲸网关ID: out_gate_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String outGateId;

    /**
     * 终端ID: terminal_id
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private String terminalId;

    /**
     * 计算日期yyyyMMdd: calculate_day
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer calculateDay;

    /**
     * 本日累计次数: amount
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Integer amount;

    /**
     * 平均温度: avg_temperature
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private BigDecimal avgTemperature;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-03 10:15:16
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getOutGateId() {
        return outGateId;
    }

    public void setOutGateId(String outGateId) {
        this.outGateId = outGateId;
    }

    public String getTerminalId() {
        return terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public Integer getCalculateDay() {
        return calculateDay;
    }

    public void setCalculateDay(Integer calculateDay) {
        this.calculateDay = calculateDay;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public BigDecimal getAvgTemperature() {
        return avgTemperature;
    }

    public void setAvgTemperature(BigDecimal avgTemperature) {
        this.avgTemperature = avgTemperature;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}