package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-03-22 14:20:27
 * @Table store_product_monitor
*/
public class StoreProductMonitor {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Long id;

    /**
     * 类型：1、临期；2、过期: type
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Integer type;

    /**
     * 店铺ID: store_id
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Integer storeId;

    /**
     * 商品ID: product_id
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Integer productId;

    /**
     * 商品合计数: total
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Integer total;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-03-22 14:20:27
      */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}