package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 19:00:00
 * @Table tool_disinfection
*/
public class ToolDisinfection {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private Integer id;

    /**
     * 前置门店ID: store_id
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private Integer storeId;

    /**
     * 消毒日期，格式：yyyyMMdd: date
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private Integer date;

    /**
     * 操作人: operator
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private String operator;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-03 19:00:00
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Integer getDate() {
        return date;
    }

    public void setDate(Integer date) {
        this.date = date;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}