package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 20:07:31
 * @Table tool_disinfection_dict
*/
public class ToolDisinfectionDict {
    /**
     * id
     * 
     * @mbg.generated 2019-04-03 20:07:31
      */
    private Long id;

    /**
     * name
     * 
     * @mbg.generated 2019-04-03 20:07:31
      */
    private String name;

    /**
     * is_delete
     * 
     * @mbg.generated 2019-04-03 20:07:31
      */
    private Integer isDelete;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-03 20:07:31
      */
    private Date createTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}