package com.ddmc.kanban.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-03 13:37:28
 * @Table tool_disinfection_item
*/
public class ToolDisinfectionItem {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private Integer id;

    /**
     * 刀具消毒记录ID: tool_disinfection_id
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private Integer toolDisinfectionId;

    /**
     * 操作人: operator
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private String operator;

    /**
     * 刀具名称: tool_name
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private String toolName;

    /**
     * 刀具数量: tool_num
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private Integer toolNum;

    /**
     * 消毒方式: disinfection_way
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private String disinfectionWay;

    /**
     * 创建时间: create_time
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-03 13:37:28
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getToolDisinfectionId() {
        return toolDisinfectionId;
    }

    public void setToolDisinfectionId(Integer toolDisinfectionId) {
        this.toolDisinfectionId = toolDisinfectionId;
    }

    public String getOperator() {
        return operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public String getToolName() {
        return toolName;
    }

    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    public Integer getToolNum() {
        return toolNum;
    }

    public void setToolNum(Integer toolNum) {
        this.toolNum = toolNum;
    }

    public String getDisinfectionWay() {
        return disinfectionWay;
    }

    public void setDisinfectionWay(String disinfectionWay) {
        this.disinfectionWay = disinfectionWay;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}