package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-30 11:34:14
 * @Table t_role
*/
public class Role {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-30 11:34:14
      */
    private Integer id;

    /**
     * role_name
     * 
     * @mbg.generated 2019-04-30 11:34:14
      */
    private String roleName;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}