package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-30 13:08:41
 * @Table t_role
*/
public class Role {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private Integer id;

    /**
     * role_name
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String roleName;

    /**
     * field1
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field1;

    /**
     * field2
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field2;

    /**
     * field3
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field3;

    /**
     * field4
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field4;

    /**
     * field5
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field5;

    /**
     * field6
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field6;

    /**
     * field7
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field7;

    /**
     * field8
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field8;

    /**
     * field9
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field9;

    /**
     * field10
     * 
     * @mbg.generated 2019-04-30 13:08:41
      */
    private String field10;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getField1() {
        return field1;
    }

    public void setField1(String field1) {
        this.field1 = field1;
    }

    public String getField2() {
        return field2;
    }

    public void setField2(String field2) {
        this.field2 = field2;
    }

    public String getField3() {
        return field3;
    }

    public void setField3(String field3) {
        this.field3 = field3;
    }

    public String getField4() {
        return field4;
    }

    public void setField4(String field4) {
        this.field4 = field4;
    }

    public String getField5() {
        return field5;
    }

    public void setField5(String field5) {
        this.field5 = field5;
    }

    public String getField6() {
        return field6;
    }

    public void setField6(String field6) {
        this.field6 = field6;
    }

    public String getField7() {
        return field7;
    }

    public void setField7(String field7) {
        this.field7 = field7;
    }

    public String getField8() {
        return field8;
    }

    public void setField8(String field8) {
        this.field8 = field8;
    }

    public String getField9() {
        return field9;
    }

    public void setField9(String field9) {
        this.field9 = field9;
    }

    public String getField10() {
        return field10;
    }

    public void setField10(String field10) {
        this.field10 = field10;
    }
}