package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author Wude
 * @Datetime @mbg.generated 2019-03-22 22:43:18
 * @Table t_test
*/
public class Test extends TestKey {
    /**
     * gender
     * 
     * @mbg.generated 2019-03-22 22:43:18
      */
    private Integer gender;

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }
}