package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author Wude
 * @Datetime @mbg.generated 2019-03-22 22:43:18
 * @Table t_test
*/
public class TestKey {
    /**
     * id_first
     * 
     * @mbg.generated 2019-03-22 22:43:18
      */
    private Integer idFirst;

    /**
     * id_two
     * 
     * @mbg.generated 2019-03-22 22:43:18
      */
    private Integer idTwo;

    public Integer getIdFirst() {
        return idFirst;
    }

    public void setIdFirst(Integer idFirst) {
        this.idFirst = idFirst;
    }

    public Integer getIdTwo() {
        return idTwo;
    }

    public void setIdTwo(Integer idTwo) {
        this.idTwo = idTwo;
    }
}