package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-03-26 15:09:58
 * @Table t_users
 */
public class User {
    /**
     * 自增长主键: id
     *
     * @mbg.generated 2019-03-26 15:09:58
     */
    private Integer id;

    /**
     * 用户名: username
     *
     * @mbg.generated 2019-03-26 15:09:58
     */
    private String username;

    /**
     * 密码: password
     *
     * @mbg.generated 2019-03-26 15:09:58
     */
    private String password;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}