package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-03-26 15:09:58
 * @Table t_user_role
 */
public class UserRole extends UserRoleKey {
}