package com.demo.boot.user.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author Wude
 * @Datetime @mbg.generated 2019-03-18 23:11:23
 * @Table t_users
*/
public class User {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-03-18 23:11:23
      */
    private Long id;

    /**
     * name
     * 
     * @mbg.generated 2019-03-18 23:11:23
      */
    private String name;

    /**
     * register_time
     * 
     * @mbg.generated 2019-03-18 23:11:23
      */
    private Date registerTime;

    /**
     * age
     * 
     * @mbg.generated 2019-03-18 23:11:23
      */
    private Integer age;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}