package com.demo.boot.user.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-17 13:46:40
 * @Table t_users
*/
public class User {
    /**
     * 自增长主键: id
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private Long id;

    /**
     * name
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String name;

    /**
     * age
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private Integer age;

    /**
     * register_time
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private Date registerTime;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private Date updateTime;

    /**
     * field1
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field1;

    /**
     * field2
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field2;

    /**
     * field3
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field3;

    /**
     * field4
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field4;

    /**
     * field5
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field5;

    /**
     * field6
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String field6;

    /**
     * description
     * 
     * @mbg.generated 2019-04-17 13:46:40
      */
    private String description;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Date getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getField1() {
        return field1;
    }

    public void setField1(String field1) {
        this.field1 = field1;
    }

    public String getField2() {
        return field2;
    }

    public void setField2(String field2) {
        this.field2 = field2;
    }

    public String getField3() {
        return field3;
    }

    public void setField3(String field3) {
        this.field3 = field3;
    }

    public String getField4() {
        return field4;
    }

    public void setField4(String field4) {
        this.field4 = field4;
    }

    public String getField5() {
        return field5;
    }

    public void setField5(String field5) {
        this.field5 = field5;
    }

    public String getField6() {
        return field6;
    }

    public void setField6(String field6) {
        this.field6 = field6;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}