package com.demo.boot.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-17-44 05:44:13
 * @mbg.generated 2018-17-44 05:44:13
 */
@Repository
public interface UserDao extends BaseDao<User, Integer> {

}