package com.demo.boot.order.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-17 15:06:50
 * @Table t_orders
*/
public class Order {
    /**
     * id
     * 
     * @mbg.generated 2019-04-17 15:06:50
      */
    private Long id;

    /**
     * order_no
     * 
     * @mbg.generated 2019-04-17 15:06:50
      */
    private String orderNo;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-17 15:06:50
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-17 15:06:50
      */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}