server:
  port: 9090
#  servlet:
#    context-path: /boot
spring:
  profiles:
    active: datasource, web
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    schema: classpath:import.sql
#    url: jdbc:mysql://localhost:3306/spring-boot
mybatis:
  config-location: classpath:mybatis-config.xml
  check-config-location: true
  mapper-locations: classpath:**/*Mapper*.xml
debug: true
#logging:
#  config: classpath:logback-spring.xml
#admin:
#  name: lbj
#  password: 123456






