package com.ddmc.reconciliation.dao;

import com.ddmc.reconciliation.model.FinanceBillOrderDetail;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-28 17:33:36
 * @mbg.generated 2019-04-28 17:33:36
*/
@Repository
public interface FinanceBillOrderDetailDao extends BaseDao<FinanceBillOrderDetail, Integer> {
}