package com.ddmc.reconciliation.dao;

import com.ddmc.reconciliation.model.FinanceBillEmail;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-28 17:38:38
 * @mbg.generated 2019-04-28 17:38:38
*/
@Repository
public interface FinanceBillEmailDao extends BaseDao<FinanceBillEmail, Integer> {
}