package com.ddmc.reconciliation.dao;

import com.ddmc.reconciliation.model.FinanceBillVendorList;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-29 16:56:05
 * @mbg.generated 2019-04-29 16:56:05
*/
@Repository
public interface FinanceBillVendorListDao extends BaseDao<FinanceBillVendorList, Integer> {
}