package com.ddmc.reconciliation.dao;

import com.ddmc.reconciliation.model.FinanceBillCollect;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-28 14:34:30
 * @mbg.generated 2019-04-28 14:34:30
*/
@Repository
public interface FinanceBillCollectDao extends BaseDao<FinanceBillCollect, Integer> {
}