package com.ddmc.reconciliation.dao;

import com.ddmc.reconciliation.model.FinanceBillRemark;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-26 19:11:15
 * @mbg.generated 2019-04-26 19:11:15
*/
@Repository
public interface FinanceBillRemarkDao extends BaseDao<FinanceBillRemark, Long> {
}