package com.demo.boot.user.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.user.model.Test;
import com.demo.boot.user.model.TestKey;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author Wude
 * @Datetime 2019-03-22 22:40:35
 * @mbg.generated 2019-03-22 22:40:35
*/
@Repository
public interface TestDao extends BaseDao<Test, TestKey> {
}