package com.demo.boot.user.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.user.model.UserRole;
import com.demo.boot.user.model.UserRoleKey;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-26 15:09:58
 * @mbg.generated 2019-03-26 15:09:58
*/
@Repository
public interface UserRoleDao extends BaseDao<UserRole, UserRoleKey> {
}