package com.demo.boot.user.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.user.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-17 14:52:24
 * @mbg.generated 2019-04-17 14:52:24
*/
@Repository
public interface UserDao extends BaseDao<User, Long> {
}