package com.demo.boot.user.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.user.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author Wude
 * @Datetime 2019-03-18 23:11:23
 * @mbg.generated 2019-03-18 23:11:23
*/
@Repository
public interface UserDao extends BaseDao<User, Long> {
}