package com.demo.boot.business.model;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date @mbg.generated 2018-09-30 15:58:45
 * @Table business
 */
public class Business {
    /**
     * : id
     *
     * @mbg.generated 2018-09-30 15:58:45
     */
    private Long id;

    /**
     * : b_no
     *
     * @mbg.generated 2018-09-30 15:58:45
     */
    private String bNo;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getbNo() {
        return bNo;
    }

    public void setbNo(String bNo) {
        this.bNo = bNo;
    }
}