package com.demo.boot.user.model;

/**
 * @Description Automatically generated by MBG, please do not manually modify it.
 * @Author dell
 * @Date @mbg.generated 2018-09-30 15:58:32
 * @Table user
*/
public class User {
    /**
     * : id
     * 
     * @mbg.generated 2018-09-30 15:58:32
      */
    private Long id;

    /**
     * : username
     * 
     * @mbg.generated 2018-09-30 15:58:32
      */
    private String username;

    /**
     * : password
     * 
     * @mbg.generated 2018-09-30 15:58:32
      */
    private String password;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}