package com.demo.boot.kanban.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.kanban.model.ProductMonitor;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-18 17:16:42
 * @mbg.generated 2019-03-18 17:16:42
*/
@Repository
public interface ProductMonitorDao extends BaseDao<ProductMonitor, Long> {
}