package com.demo.boot.kanban.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.kanban.model.Product;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-15 19:53:23
 * @mbg.generated 2019-03-15 19:53:23
*/
@Repository
public interface ProductDao extends BaseDao<Product, Integer> {
}