package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.CarAvgTemperature;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 16:35:56
 * @mbg.generated 2019-04-03 16:35:56
*/
@Repository
public interface CarAvgTemperatureDao extends BaseDao<CarAvgTemperature, Long> {
}