package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.CarHistoryData;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-04 10:52:01
 * @mbg.generated 2019-04-04 10:52:01
*/
@Repository
public interface CarHistoryDataDao extends BaseDao<CarHistoryData, Long> {
}