package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.PestInspectionMouseDict;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-04 10:35:23
 * @mbg.generated 2019-04-04 10:35:23
*/
@Repository
public interface PestInspectionMouseDictDao extends BaseDao<PestInspectionMouseDict, Integer> {
}