package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.ProductMonitor;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-11 15:52:40
 * @mbg.generated 2019-04-11 15:52:40
*/
@Repository
public interface ProductMonitorDao extends BaseDao<ProductMonitor, Long> {
}