package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.ProductBatch;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-18 09:33:27
 * @mbg.generated 2019-04-18 09:33:27
*/
@Repository
public interface ProductBatchDao extends BaseDao<ProductBatch, Integer> {
}