package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.RecycleAreaInspection;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-04 11:26:39
 * @mbg.generated 2019-04-04 11:26:39
*/
@Repository
public interface RecycleAreaInspectionDao extends BaseDao<RecycleAreaInspection, Integer> {
}