package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.StoreInspection;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 16:00:27
 * @mbg.generated 2019-04-03 16:00:27
*/
@Repository
public interface StoreInspectionDao extends BaseDao<StoreInspection, Integer> {
}