package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.StoreInspectionRectify;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 19:17:12
 * @mbg.generated 2019-04-03 19:17:12
*/
@Repository
public interface StoreInspectionRectifyDao extends BaseDao<StoreInspectionRectify, Integer> {
}