package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.ToolDisinfectionItem;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 19:04:06
 * @mbg.generated 2019-04-03 19:04:06
*/
@Repository
public interface ToolDisinfectionItemDao extends BaseDao<ToolDisinfectionItem, Integer> {
}