package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.ToolDisinfection;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 19:00:00
 * @mbg.generated 2019-04-03 19:00:00
*/
@Repository
public interface ToolDisinfectionDao extends BaseDao<ToolDisinfection, Integer> {
}