package com.ddmc.kanban.dao.kanban;

import com.ddmc.kanban.model.ToolDisinfectionDict;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 20:07:31
 * @mbg.generated 2019-04-03 20:07:31
*/
@Repository
public interface ToolDisinfectionDictDao extends BaseDao<ToolDisinfectionDict, Long> {
}