package com.demo.boot.order.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.order.model.Order;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-17 15:06:50
 * @mbg.generated 2019-04-17 15:06:50
*/
@Repository
public interface OrderDao extends BaseDao<Order, Long> {
}