package com.ddmc.reconciliation.model;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-26 19:11:15
 * @Table finance_bill_remark
*/
public class FinanceBillRemark {
    /**
     * id
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Long id;

    /**
     * 单据id：采购单id，退货单id : source_id
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Long sourceId;

    /**
     * 单据类型 1-采购单，2-退货单: type
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Integer type;

    /**
     * 财务备注内容: remark
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private String remark;

    /**
     * 操作人: operator
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Long operator;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Date updateTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getOperator() {
        return operator;
    }

    public void setOperator(Long operator) {
        this.operator = operator;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}