package com.ddmc.reconciliation.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-29 16:56:05
 * @Table finance_bill_order_detail
*/
public class FinanceBillOrderDetail {
    /**
     * 业务主键 自增: id
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer id;

    /**
     * 状态：0=无效，1=有效: status
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer status;

    /**
     * scm原数据id: biz_id
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer bizId;

    /**
     * 财务单据编号: finance_biz_id
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private String financeBizId;

    /**
     * 财务单据类型：1=采购单，2=退货单，3=付款单: finance_biz_type
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer financeBizType;

    /**
     * 财务单据子类型：10=采购单-入库完成，11=采购单-红冲入库，12=采购单-调整入库，20=退货单，30=付款单-结算款，31=付款单-预付款，32=付款单-红冲预付: finance_biz_subtype
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer financeBizSubtype;

    /**
     * 财务单据状态：单据对应状态：1 已完成，2 已付款等: finance_biz_status
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer financeBizStatus;

    /**
     * 财务单据金额: finance_biz_amount
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private BigDecimal financeBizAmount;

    /**
     * 业务完成时间: finance_biz_finish_time
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Date financeBizFinishTime;

    /**
     * 供应商ID: vendor_id
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer vendorId;

    /**
     * 供应商名称: vendor_name
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private String vendorName;

    /**
     * 供应商状态: vendor_status
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer vendorStatus;

    /**
     * 供应商负责组  ?: vendor_resp_groups
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private String vendorRespGroups;

    /**
     * 财务对账状态：0=未对账，1=已对账: op_status
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer opStatus;

    /**
     * 金蝶应付账款: jindie_amount
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private BigDecimal jindieAmount;

    /**
     * 差额: balance
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private BigDecimal balance;

    /**
     * 叮咚应付金额: ddmc_amount
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private BigDecimal ddmcAmount;

    /**
     * 为了处理付款单红冲预付、采购单红冲入库金额、调整入库金额等场景的情况下 数据唯一: biz_id_subtype
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Integer bizIdSubtype;

    /**
     * 是否同步 0 未同步 1 已同步: sync
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Long sync;

    /**
     * 记录创建时间: create_time
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Date createTime;

    /**
     * 记录更新时间: update_time
     * 
     * @mbg.generated 2019-04-29 16:56:05
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getBizId() {
        return bizId;
    }

    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    public String getFinanceBizId() {
        return financeBizId;
    }

    public void setFinanceBizId(String financeBizId) {
        this.financeBizId = financeBizId;
    }

    public Integer getFinanceBizType() {
        return financeBizType;
    }

    public void setFinanceBizType(Integer financeBizType) {
        this.financeBizType = financeBizType;
    }

    public Integer getFinanceBizSubtype() {
        return financeBizSubtype;
    }

    public void setFinanceBizSubtype(Integer financeBizSubtype) {
        this.financeBizSubtype = financeBizSubtype;
    }

    public Integer getFinanceBizStatus() {
        return financeBizStatus;
    }

    public void setFinanceBizStatus(Integer financeBizStatus) {
        this.financeBizStatus = financeBizStatus;
    }

    public BigDecimal getFinanceBizAmount() {
        return financeBizAmount;
    }

    public void setFinanceBizAmount(BigDecimal financeBizAmount) {
        this.financeBizAmount = financeBizAmount;
    }

    public Date getFinanceBizFinishTime() {
        return financeBizFinishTime;
    }

    public void setFinanceBizFinishTime(Date financeBizFinishTime) {
        this.financeBizFinishTime = financeBizFinishTime;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public Integer getVendorStatus() {
        return vendorStatus;
    }

    public void setVendorStatus(Integer vendorStatus) {
        this.vendorStatus = vendorStatus;
    }

    public String getVendorRespGroups() {
        return vendorRespGroups;
    }

    public void setVendorRespGroups(String vendorRespGroups) {
        this.vendorRespGroups = vendorRespGroups;
    }

    public Integer getOpStatus() {
        return opStatus;
    }

    public void setOpStatus(Integer opStatus) {
        this.opStatus = opStatus;
    }

    public BigDecimal getJindieAmount() {
        return jindieAmount;
    }

    public void setJindieAmount(BigDecimal jindieAmount) {
        this.jindieAmount = jindieAmount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public BigDecimal getDdmcAmount() {
        return ddmcAmount;
    }

    public void setDdmcAmount(BigDecimal ddmcAmount) {
        this.ddmcAmount = ddmcAmount;
    }

    public Integer getBizIdSubtype() {
        return bizIdSubtype;
    }

    public void setBizIdSubtype(Integer bizIdSubtype) {
        this.bizIdSubtype = bizIdSubtype;
    }

    public Long getSync() {
        return sync;
    }

    public void setSync(Long sync) {
        this.sync = sync;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}