package com.ddmc.reconciliation.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-26 19:11:15
 * @Table finance_bill_vendor_list
*/
public class FinanceBillVendorList {
    /**
     * 主键: id
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Integer id;

    /**
     * 供应商ID: vendor_id
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Integer vendorId;

    /**
     * 供应商名称: vendor_name
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private String vendorName;

    /**
     * 供应商状态: vendor_status
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Integer vendorStatus;

    /**
     * 供应商负责组 多个用，分割: vendor_resp_groups
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private String vendorRespGroups;

    /**
     * 系统应付账款: ddmc_amount
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private BigDecimal ddmcAmount;

    /**
     * 金蝶应付账款: jindie_amount
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private BigDecimal jindieAmount;

    /**
     * 差额: balance
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private BigDecimal balance;

    /**
     * 财务对账状态：0=未对账，1=已对账: op_status
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Integer opStatus;

    /**
     * 开始时间: crearte_time
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Date crearteTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-26 19:11:15
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public Integer getVendorStatus() {
        return vendorStatus;
    }

    public void setVendorStatus(Integer vendorStatus) {
        this.vendorStatus = vendorStatus;
    }

    public String getVendorRespGroups() {
        return vendorRespGroups;
    }

    public void setVendorRespGroups(String vendorRespGroups) {
        this.vendorRespGroups = vendorRespGroups;
    }

    public BigDecimal getDdmcAmount() {
        return ddmcAmount;
    }

    public void setDdmcAmount(BigDecimal ddmcAmount) {
        this.ddmcAmount = ddmcAmount;
    }

    public BigDecimal getJindieAmount() {
        return jindieAmount;
    }

    public void setJindieAmount(BigDecimal jindieAmount) {
        this.jindieAmount = jindieAmount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Integer getOpStatus() {
        return opStatus;
    }

    public void setOpStatus(Integer opStatus) {
        this.opStatus = opStatus;
    }

    public Date getCrearteTime() {
        return crearteTime;
    }

    public void setCrearteTime(Date crearteTime) {
        this.crearteTime = crearteTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}