package com.ddmc.reconciliation.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-28 14:34:30
 * @Table finance_bill_collect
*/
public class FinanceBillCollect {
    /**
     * 主键: id
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Integer id;

    /**
     * 系统应付金额: ddmc_amount
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private BigDecimal ddmcAmount;

    /**
     * 金蝶应付金额: jindie_amount
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private BigDecimal jindieAmount;

    /**
     * 差额: balance
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private BigDecimal balance;

    /**
     * 财务对账状态：0=未对账，1=已对账: op_status
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Integer opStatus;

    /**
     * 对账人: op_people
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private String opPeople;

    /**
     * 对账日期 (对账人操作的日期): op_time
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Date opTime;

    /**
     * 是否同步 0 未同步 1 已同步: sync
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Long sync;

    /**
     * 创建日期: create_time
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Date createTime;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-28 14:34:30
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public BigDecimal getDdmcAmount() {
        return ddmcAmount;
    }

    public void setDdmcAmount(BigDecimal ddmcAmount) {
        this.ddmcAmount = ddmcAmount;
    }

    public BigDecimal getJindieAmount() {
        return jindieAmount;
    }

    public void setJindieAmount(BigDecimal jindieAmount) {
        this.jindieAmount = jindieAmount;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Integer getOpStatus() {
        return opStatus;
    }

    public void setOpStatus(Integer opStatus) {
        this.opStatus = opStatus;
    }

    public String getOpPeople() {
        return opPeople;
    }

    public void setOpPeople(String opPeople) {
        this.opPeople = opPeople;
    }

    public Date getOpTime() {
        return opTime;
    }

    public void setOpTime(Date opTime) {
        this.opTime = opTime;
    }

    public Long getSync() {
        return sync;
    }

    public void setSync(Long sync) {
        this.sync = sync;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}