package com.ddmc.reconciliation.dao.scm;

import com.ddmc.reconciliation.model.scm.PayRecord;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-28 15:16:04
 * @mbg.generated 2019-04-28 15:16:04
*/
@Repository
public interface PayRecordDao extends BaseDao<PayRecord, Integer> {
}