package com.ddmc.reconciliation.dao.scm;

import com.ddmc.reconciliation.model.scm.Purchase;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-28 15:27:25
 * @mbg.generated 2019-04-28 15:27:25
*/
@Repository
public interface PurchaseDao extends BaseDao<Purchase, Integer> {
}