package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.BatchVersion;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-02 09:45:34
 * @mbg.generated 2019-04-02 09:45:34
*/
@Repository
public interface BatchVersionDao extends BaseDao<BatchVersion, Integer> {
}