package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.Car;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-02 14:13:02
 * @mbg.generated 2019-04-02 14:13:02
*/
@Repository
public interface CarDao extends BaseDao<Car, Long> {
}