package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.GeneralPackage;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-29 15:06:07
 * @mbg.generated 2019-03-29 15:06:07
*/
@Repository
public interface GeneralPackageDao extends BaseDao<GeneralPackage, Integer> {
}