package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.RecycleAreaInspection;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-02 19:33:35
 * @mbg.generated 2019-04-02 19:33:35
*/
@Repository
public interface RecycleAreaInspectionDao extends BaseDao<RecycleAreaInspection, Integer> {
}