package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.RefrigerationHouseGate;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-03 10:15:16
 * @mbg.generated 2019-04-03 10:15:16
*/
@Repository
public interface RefrigerationHouseGateDao extends BaseDao<RefrigerationHouseGate, Integer> {
}