package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.RefrigerationHouse;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-02 14:17:38
 * @mbg.generated 2019-04-02 14:17:38
*/
@Repository
public interface RefrigerationHouseDao extends BaseDao<RefrigerationHouse, Integer> {
}