package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.StoreProductBatch;
import com.ddmc.kanban.model.StoreProductBatchKey;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-04-09 15:49:24
 * @mbg.generated 2019-04-09 15:49:24
*/
@Repository
public interface StoreProductBatchDao extends BaseDao<StoreProductBatch, StoreProductBatchKey> {
}