package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.Store;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-21 16:25:20
 * @mbg.generated 2019-03-21 16:25:20
*/
@Repository
public interface StoreDao extends BaseDao<Store, Integer> {
}