package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.StoreProductMonitor;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-19 13:01:56
 * @mbg.generated 2019-03-19 13:01:56
*/
@Repository
public interface StoreProductMonitorDao extends BaseDao<StoreProductMonitor, Long> {
}