package com.ddmc.kanban.dao;

import com.ddmc.kanban.model.Version;
import com.demo.boot.base.dao.BaseDao;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime 2019-03-31 13:29:42
 * @mbg.generated 2019-03-31 13:29:42
*/
@Repository
public interface VersionDao extends BaseDao<Version, Integer> {
}