package com.demo.boot.user.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.user.model.User;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-09-30 15:58:32
 * @mbg.generated 2018-09-30 15:58:32
*/
@Repository
public interface UserDao extends BaseDao<User, Long> {
}