# Web功能端口
server:
  port: 9090
# 激活的spring.profiles
spring:
  profiles:
    active: datasource, web, redis
# Mybatis
#mybatis:
#  config-location: classpath:mybatis-config.xml #为什么用classpath*就报错找不到资源文件了?
#  check-config-location: true
#  mapper-locations: classpath*:mapper/*.xml #为什么classpath和classpath*等效?
# 日志设置, Logback作为日志实现框架配置
debug: false #默认情况下，spring boot从控制台打印出来的日志级别只有ERROR, WARN 还有INFO
logging:
  config: classpath:logback.xml


log:
  exclude: core,log
privilege:
  collect:
    init: false
    enable: true





