package com.demo.boot.business.dao;

import com.demo.boot.base.dao.BaseDao;
import com.demo.boot.business.model.Business;
import org.springframework.stereotype.Repository;

/**
 * @Description Automatically generated by MBG.
 * @Author dell
 * @Date 2018-09-30 15:58:45
 * @mbg.generated 2018-09-30 15:58:45
*/
@Repository
public interface BusinessDao extends BaseDao<Business, Long> {
}