package com.ddmc.reconciliation.model.scm;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-28 15:16:04
 * @Table pay_record
 */
public class PayRecord {
    /**
     * id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer id;

    /**
     * vendor_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer vendorId;

    /**
     * finish_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date finishTime;

    /**
     * submit_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date submitTime;

    /**
     * 用途: use_to
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String useTo;

    /**
     * 备注: remark
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String remark;

    /**
     * 预支付总金额: plan_total_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal planTotalAmount;

    /**
     * 实际支付金额: real_total_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal realTotalAmount;

    /**
     * create_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date createTime;

    /**
     * update_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date updateTime;

    /**
     * 创建人: create_user
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String createUser;

    /**
     * 更新人: update_user
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String updateUser;

    /**
     * 财务操作人: finance_update_user
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String financeUpdateUser;

    /**
     * 状态: status
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer status;

    /**
     * 提交人: submit_user
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String submitUser;

    /**
     * 最后付款日: last_pay_day
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String lastPayDay;

    /**
     * 审批人: approver
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String approver;

    /**
     * 发票选项: invoice_option
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer invoiceOption;

    /**
     * 最早付款日: earliest_pay_day
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String earliestPayDay;

    /**
     * 枚举值  1：结算单； 2：预付单，默认为1 结算单: pay_type
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer payType;

    /**
     * 结算金额: settlement_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal settlementAmount;

    /**
     * 已预付金额: prepay_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal prepayAmount;

    /**
     * 付款银行ID，关联pay_bank主键ID: pay_bank_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer payBankId;

    /**
     * jsonå­—ç¬¦ä¸²,[{source:æ¥æº,type:0æœ‰å•å· 1è‡ªå®šä¹‰ï¼Œtype_nameï¼šé‡‡è´­å•ã€é€€æ¬¾å•,finish_time:å®Œæˆæ—¶é—´,plan_amount:è®¡åˆ’é‡‘é¢,real_amount:å®žæ”¶é‡‘é¢,audit_amount:å®¡æ ¸é‡‘é¢}]: details
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String details;

    /**
     * 供应商信息：{vendor_id,vendor_name,bank_name,account_name}: vendor_info
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String vendorInfo;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public Date getSubmitTime() {
        return submitTime;
    }

    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    public String getUseTo() {
        return useTo;
    }

    public void setUseTo(String useTo) {
        this.useTo = useTo;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public BigDecimal getPlanTotalAmount() {
        return planTotalAmount;
    }

    public void setPlanTotalAmount(BigDecimal planTotalAmount) {
        this.planTotalAmount = planTotalAmount;
    }

    public BigDecimal getRealTotalAmount() {
        return realTotalAmount;
    }

    public void setRealTotalAmount(BigDecimal realTotalAmount) {
        this.realTotalAmount = realTotalAmount;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreateUser() {
        return createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public String getFinanceUpdateUser() {
        return financeUpdateUser;
    }

    public void setFinanceUpdateUser(String financeUpdateUser) {
        this.financeUpdateUser = financeUpdateUser;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getSubmitUser() {
        return submitUser;
    }

    public void setSubmitUser(String submitUser) {
        this.submitUser = submitUser;
    }

    public String getLastPayDay() {
        return lastPayDay;
    }

    public void setLastPayDay(String lastPayDay) {
        this.lastPayDay = lastPayDay;
    }

    public String getApprover() {
        return approver;
    }

    public void setApprover(String approver) {
        this.approver = approver;
    }

    public Integer getInvoiceOption() {
        return invoiceOption;
    }

    public void setInvoiceOption(Integer invoiceOption) {
        this.invoiceOption = invoiceOption;
    }

    public String getEarliestPayDay() {
        return earliestPayDay;
    }

    public void setEarliestPayDay(String earliestPayDay) {
        this.earliestPayDay = earliestPayDay;
    }

    public Integer getPayType() {
        return payType;
    }

    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    public BigDecimal getSettlementAmount() {
        return settlementAmount;
    }

    public void setSettlementAmount(BigDecimal settlementAmount) {
        this.settlementAmount = settlementAmount;
    }

    public BigDecimal getPrepayAmount() {
        return prepayAmount;
    }

    public void setPrepayAmount(BigDecimal prepayAmount) {
        this.prepayAmount = prepayAmount;
    }

    public Integer getPayBankId() {
        return payBankId;
    }

    public void setPayBankId(Integer payBankId) {
        this.payBankId = payBankId;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getVendorInfo() {
        return vendorInfo;
    }

    public void setVendorInfo(String vendorInfo) {
        this.vendorInfo = vendorInfo;
    }
}