package com.ddmc.reconciliation.model.scm;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-28 15:16:04
 * @Table purchase
 */
public class Purchase {
    /**
     * purchase_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer purchaseId;

    /**
     * vendor_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer vendorId;

    /**
     * store_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer storeId;

    /**
     * create_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date createTime;

    /**
     * delivery_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date deliveryTime;

    /**
     * purchase_title
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String purchaseTitle;

    /**
     * 状态, 0:未完成,1:已完成: status
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer status;

    /**
     * 完成草稿时间: draft_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date draftTime;

    /**
     * amount_total
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal amountTotal;

    /**
     * real_amount_total
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal realAmountTotal;

    /**
     * 创建人: creater
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String creater;

    /**
     * update_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date updateTime;

    /**
     * 财务处理状态: finance_status
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer financeStatus;

    /**
     * 备注单号: finance_remark
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String financeRemark;

    /**
     * 处理时间: finance_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date financeTime;

    /**
     * 处理人: finance_operator
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String financeOperator;

    /**
     * 计划ID: plan_id
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer planId;

    /**
     * 更新人: update_user
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String updateUser;

    /**
     * 异常 超时未处理 : is_timeout
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer isTimeout;

    /**
     * type_ids
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String typeIds;

    /**
     * 结算总金额: settlement_amount_total
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal settlementAmountTotal;

    /**
     * 沟通时效 30 60 90: communicate_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer communicateTime;

    /**
     * 温度: temperature
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String temperature;

    /**
     * 车内环境：正常，一般，异味脏污: car_environment
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer carEnvironment;

    /**
     * 品控状态: quality_control_status
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer qualityControlStatus;

    /**
     * 杂项总金额: additional_total
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal additionalTotal;

    /**
     * 到货: is_arrival
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer isArrival;

    /**
     * 检测时间: quality_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date qualityTime;

    /**
     * 收货处理人: receive_operator
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String receiveOperator;

    /**
     * 计划到货时间: plan_delivery_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date planDeliveryTime;

    /**
     * 是否补货采购单:0否 1是: is_replenishment
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer isReplenishment;

    /**
     * 是否称重清点完成:0否 1是: is_weigh_completed
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer isWeighCompleted;

    /**
     * 是否支持预付，枚举值  0：否； 1：是，默认0: is_prepay
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Integer isPrepay;

    /**
     * 采购单完成之后的调整金额总计: adjustment_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal adjustmentAmount;

    /**
     * 结算总金额, 结算总金额= 商品结算总金额+杂项金额+调整金额: final_settlement_amount
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private BigDecimal finalSettlementAmount;

    /**
     * 采购单完成时间: finish_time
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private Date finishTime;

    /**
     * 商品json字符串,[{product_id,product_name,amount:采购量,real_amount:实收数量,price}]: products
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String products;

    /**
     * 导入日志: import_log
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String importLog;

    /**
     * 图片: images
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String images;

    /**
     * 供货商签名: supplier_sign
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String supplierSign;

    /**
     * 附加成本: additional
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String additional;

    /**
     * 调整费用json  [{"adjustment_type_id":"1","adjustment_type_name":"运输费","adjustment_amount":"2.3654","remark": "备注","caozuo_name":"操作人","create_time":"2019-03-01 11:11:11"}]: adjustment_amount_detail
     *
     * @mbg.generated 2019-04-28 15:16:04
     */
    private String adjustmentAmountDetail;

    public Integer getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    public String getPurchaseTitle() {
        return purchaseTitle;
    }

    public void setPurchaseTitle(String purchaseTitle) {
        this.purchaseTitle = purchaseTitle;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getDraftTime() {
        return draftTime;
    }

    public void setDraftTime(Date draftTime) {
        this.draftTime = draftTime;
    }

    public BigDecimal getAmountTotal() {
        return amountTotal;
    }

    public void setAmountTotal(BigDecimal amountTotal) {
        this.amountTotal = amountTotal;
    }

    public BigDecimal getRealAmountTotal() {
        return realAmountTotal;
    }

    public void setRealAmountTotal(BigDecimal realAmountTotal) {
        this.realAmountTotal = realAmountTotal;
    }

    public String getCreater() {
        return creater;
    }

    public void setCreater(String creater) {
        this.creater = creater;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getFinanceStatus() {
        return financeStatus;
    }

    public void setFinanceStatus(Integer financeStatus) {
        this.financeStatus = financeStatus;
    }

    public String getFinanceRemark() {
        return financeRemark;
    }

    public void setFinanceRemark(String financeRemark) {
        this.financeRemark = financeRemark;
    }

    public Date getFinanceTime() {
        return financeTime;
    }

    public void setFinanceTime(Date financeTime) {
        this.financeTime = financeTime;
    }

    public String getFinanceOperator() {
        return financeOperator;
    }

    public void setFinanceOperator(String financeOperator) {
        this.financeOperator = financeOperator;
    }

    public Integer getPlanId() {
        return planId;
    }

    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Integer getIsTimeout() {
        return isTimeout;
    }

    public void setIsTimeout(Integer isTimeout) {
        this.isTimeout = isTimeout;
    }

    public String getTypeIds() {
        return typeIds;
    }

    public void setTypeIds(String typeIds) {
        this.typeIds = typeIds;
    }

    public BigDecimal getSettlementAmountTotal() {
        return settlementAmountTotal;
    }

    public void setSettlementAmountTotal(BigDecimal settlementAmountTotal) {
        this.settlementAmountTotal = settlementAmountTotal;
    }

    public Integer getCommunicateTime() {
        return communicateTime;
    }

    public void setCommunicateTime(Integer communicateTime) {
        this.communicateTime = communicateTime;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public Integer getCarEnvironment() {
        return carEnvironment;
    }

    public void setCarEnvironment(Integer carEnvironment) {
        this.carEnvironment = carEnvironment;
    }

    public Integer getQualityControlStatus() {
        return qualityControlStatus;
    }

    public void setQualityControlStatus(Integer qualityControlStatus) {
        this.qualityControlStatus = qualityControlStatus;
    }

    public BigDecimal getAdditionalTotal() {
        return additionalTotal;
    }

    public void setAdditionalTotal(BigDecimal additionalTotal) {
        this.additionalTotal = additionalTotal;
    }

    public Integer getIsArrival() {
        return isArrival;
    }

    public void setIsArrival(Integer isArrival) {
        this.isArrival = isArrival;
    }

    public Date getQualityTime() {
        return qualityTime;
    }

    public void setQualityTime(Date qualityTime) {
        this.qualityTime = qualityTime;
    }

    public String getReceiveOperator() {
        return receiveOperator;
    }

    public void setReceiveOperator(String receiveOperator) {
        this.receiveOperator = receiveOperator;
    }

    public Date getPlanDeliveryTime() {
        return planDeliveryTime;
    }

    public void setPlanDeliveryTime(Date planDeliveryTime) {
        this.planDeliveryTime = planDeliveryTime;
    }

    public Integer getIsReplenishment() {
        return isReplenishment;
    }

    public void setIsReplenishment(Integer isReplenishment) {
        this.isReplenishment = isReplenishment;
    }

    public Integer getIsWeighCompleted() {
        return isWeighCompleted;
    }

    public void setIsWeighCompleted(Integer isWeighCompleted) {
        this.isWeighCompleted = isWeighCompleted;
    }

    public Integer getIsPrepay() {
        return isPrepay;
    }

    public void setIsPrepay(Integer isPrepay) {
        this.isPrepay = isPrepay;
    }

    public BigDecimal getAdjustmentAmount() {
        return adjustmentAmount;
    }

    public void setAdjustmentAmount(BigDecimal adjustmentAmount) {
        this.adjustmentAmount = adjustmentAmount;
    }

    public BigDecimal getFinalSettlementAmount() {
        return finalSettlementAmount;
    }

    public void setFinalSettlementAmount(BigDecimal finalSettlementAmount) {
        this.finalSettlementAmount = finalSettlementAmount;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public String getProducts() {
        return products;
    }

    public void setProducts(String products) {
        this.products = products;
    }

    public String getImportLog() {
        return importLog;
    }

    public void setImportLog(String importLog) {
        this.importLog = importLog;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getSupplierSign() {
        return supplierSign;
    }

    public void setSupplierSign(String supplierSign) {
        this.supplierSign = supplierSign;
    }

    public String getAdditional() {
        return additional;
    }

    public void setAdditional(String additional) {
        this.additional = additional;
    }

    public String getAdjustmentAmountDetail() {
        return adjustmentAmountDetail;
    }

    public void setAdjustmentAmountDetail(String adjustmentAmountDetail) {
        this.adjustmentAmountDetail = adjustmentAmountDetail;
    }
}