package com.ddmc.reconciliation.model.scm;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-28 15:27:25
 * @Table return_purchase
*/
public class ReturnPurchase {
    /**
     * return_id
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer returnId;

    /**
     * purchase_id
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer purchaseId;

    /**
     * vendor_id
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer vendorId;

    /**
     * store_id
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer storeId;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Date createTime;

    /**
     * delivery_time
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Date deliveryTime;

    /**
     * 商品类型: type_ids
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String typeIds;

    /**
     * 状态, 0:待退货,1:待编辑,2:完成,-1:废弃: status
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer status;

    /**
     * 完成草稿时间: draft_time
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Date draftTime;

    /**
     * 创建人: creater
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String creater;

    /**
     * amount_total
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private BigDecimal amountTotal;

    /**
     * real_amount_total
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private BigDecimal realAmountTotal;

    /**
     * 更新时间: update_time
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Date updateTime;

    /**
     * 财务处理状态: finance_status
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer financeStatus;

    /**
     * 备注单号: finance_remark
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String financeRemark;

    /**
     * 处理时间: finance_time
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Date financeTime;

    /**
     * 处理人: finance_operator
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String financeOperator;

    /**
     * 更新人: update_user
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String updateUser;

    /**
     * 异常 超时未处理 : is_timeout
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private Integer isTimeout;

    /**
     * 商品json字符串,[{product_id,product_name,unit_name,amount:计划退货数量,real_amount:实际退货数量,price}]: products
     * 
     * @mbg.generated 2019-04-28 15:27:25
      */
    private String products;

    public Integer getReturnId() {
        return returnId;
    }

    public void setReturnId(Integer returnId) {
        this.returnId = returnId;
    }

    public Integer getPurchaseId() {
        return purchaseId;
    }

    public void setPurchaseId(Integer purchaseId) {
        this.purchaseId = purchaseId;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public Integer getStoreId() {
        return storeId;
    }

    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getDeliveryTime() {
        return deliveryTime;
    }

    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    public String getTypeIds() {
        return typeIds;
    }

    public void setTypeIds(String typeIds) {
        this.typeIds = typeIds;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getDraftTime() {
        return draftTime;
    }

    public void setDraftTime(Date draftTime) {
        this.draftTime = draftTime;
    }

    public String getCreater() {
        return creater;
    }

    public void setCreater(String creater) {
        this.creater = creater;
    }

    public BigDecimal getAmountTotal() {
        return amountTotal;
    }

    public void setAmountTotal(BigDecimal amountTotal) {
        this.amountTotal = amountTotal;
    }

    public BigDecimal getRealAmountTotal() {
        return realAmountTotal;
    }

    public void setRealAmountTotal(BigDecimal realAmountTotal) {
        this.realAmountTotal = realAmountTotal;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getFinanceStatus() {
        return financeStatus;
    }

    public void setFinanceStatus(Integer financeStatus) {
        this.financeStatus = financeStatus;
    }

    public String getFinanceRemark() {
        return financeRemark;
    }

    public void setFinanceRemark(String financeRemark) {
        this.financeRemark = financeRemark;
    }

    public Date getFinanceTime() {
        return financeTime;
    }

    public void setFinanceTime(Date financeTime) {
        this.financeTime = financeTime;
    }

    public String getFinanceOperator() {
        return financeOperator;
    }

    public void setFinanceOperator(String financeOperator) {
        this.financeOperator = financeOperator;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Integer getIsTimeout() {
        return isTimeout;
    }

    public void setIsTimeout(Integer isTimeout) {
        this.isTimeout = isTimeout;
    }

    public String getProducts() {
        return products;
    }

    public void setProducts(String products) {
        this.products = products;
    }
}