package com.ddmc.reconciliation.model.scm;

import java.util.Date;

/**
 * @Description Automatically generated by MBG.
 * @Author ddmc
 * @Datetime @mbg.generated 2019-04-28 15:16:04
 * @Table vendor_responsible_group_relation
*/
public class VendorResponsibleGroupRelation {
    /**
     * id
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private Integer id;

    /**
     * 负责组id: group_id
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private String groupId;

    /**
     * 负责组名称: group_name
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private String groupName;

    /**
     * 供应商id: vendor_id
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private Integer vendorId;

    /**
     * 更新人: update_user
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private String updateUser;

    /**
     * 是否已删除: is_deleted
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private Boolean isDeleted;

    /**
     * create_time
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private Date createTime;

    /**
     * update_time
     * 
     * @mbg.generated 2019-04-28 15:16:04
      */
    private Date updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Integer getVendorId() {
        return vendorId;
    }

    public void setVendorId(Integer vendorId) {
        this.vendorId = vendorId;
    }

    public String getUpdateUser() {
        return updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    public Boolean getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}